# Generated by Django 3.2 on 2021-04-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(default='11.04.2021')),
                ('end_date', models.DateField(default='11.04.2021')),
                ('number_of_lectures', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
